(#41) Preview of sign to matched literal
Wign/Wign-design-v2 pull request #57
Opened 2020-01-27 19:38 UTC by Kennik89

Check the translations of this literal for this language and return all signs for previewing. It avoids people to upload duplicate signs.

2020-01-27 19:39 UTC, Kennik89 commented
This resolves #41

2020-02-01 11:31 UTC, Thanerik requested changes

2020-02-01 11:31 UTC, Thanerik commented on graphql/schema.graphql
> +        @field(resolver: "App\\GraphQL\\TranslationEndpoints@previewSigns")
Gør @Search annotationen ikke det hele ovenstående per automatisk? Selvfølgelig skal vi jo også have likes og sorteret by likes med... men der er vist nogle ekstra annotationer der kan hjælpe? Men ellers ser det fint ud!

2020-02-01 11:31 UTC, Thanerik commented on app/Services/WordService.php
> +        return $this->wordRepository->allSigned()->whereLanguageId($language->id)->whereLiteral($literal)->first();
Dette laver ét database kald hvor det fetcher ALLE signs. Og dernæst laver den så filtering lokalt i backend. Det kan påvirke memory-performance den dag vi har 1 mio signs (Eller endda før). Bedre at lave filteringerne direkte på Eleqount-niveauet (Altså database).

2020-02-02 14:57 UTC, Kennik89 commented on graphql/schema.graphql
> +        @field(resolver: "App\\GraphQL\\TranslationEndpoints@previewSigns")
Udover dem du nævnte skal der også filtrer sproget, hvorfor jeg tror stadig det er lettere at gøre den fra Laravel side.

2020-02-02 15:09 UTC, Kennik89 commented on app/Services/WordService.php
> +        return $this->wordRepository->allSigned()->whereLanguageId($language->id)->whereLiteral($literal)->first();
jeg regnede med at allSigned returnerer eloquent builder. Den er ændret.

2020-02-02 18:38 UTC, Thanerik approved these changes

2020-02-02 21:56 UTC, merged